lr: 0.0001
min_lr: 0.00001
weight_decay: 0.000001 # l2 norm
patience: 5 # Number of epochs with no improvement after which learning rate will be reduced
es_patience: 5 #patience for early stop

input_emb_size: 768 #bert size
item_dim: 64
hid_units: [200, 80, 1]