name: IV4Rec_I_NRHUB

item_dim: 64
embedding_size: 768
Dense_dim: 200
lr: 0.0001
min_lr: 0.00001
weight_decay: 0.0000001 # l2 norm
patience: 5 #Number of epochs with no improvement after which learning rate will be reduced
es_patience: 5 #patience for early stop
history_length: 50

l2 : 0.0000001

IV_NET:

  lambda: 0.01
  item_IV_NET:
    hid_units: [256, 64]
    dropout: 0.1

    lambda: 0.01


item_Agg:
  input_dim: 128
  hid_units: [1]
