name: NRHUB_wo_src
embedding_size: 768
Dense_dim: 200

lr: 0.0001
min_lr: 0.00001
weight_decay: 0.000001 # l2 norm
patience: 5 #Number of epochs with no improvement after which learning rate will be reduced
es_patience: 5 #patience for early stop

embedding_size: 768 #bert
qry_emb_size: 768
item_emb: 64

Dense_item: 200

history_length: 50